service:
  smpp:
  - 
    server:
      addr: localhost
      port: 5588
      user: smpp
      password: test
    client:
      bind-type: transmitter
      conn-num: 5
    message:
      send:
        src: 
          npi: 1
          ton: 1
          oaddr: 1234
        dst:
          ton: 1
          npi: 1
          daddr:
            prefix: 123
            suffix: 000
            generate-length: 6
        require-sr: false
        content: just a test message without concat
  - 
    server:
      addr: localhost
      port: 5588
      user: smpp
      password: test
    client:
      bind-type: transceiver
      conn-num: 5
    message:
      send:
        src: 
          npi: 1
          ton: 1
          oaddr: 1234
        dst:
          ton: 1
          npi: 1
          daddr:
            prefix: 123
            suffix: 000
            generate-length: 6
        require-sr: false
        content: just a test message without concat
  - 
    server:
      addr: localhost
      port: 5588
      user: smpp
      password: test
    client:
      bind-type: receiver
      conn-num: 10
  rest:
    addr: 0.0.0.0
    port: 8080
  log:
    level: info